### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by Paul-Ndirangu**

### CODE REVIEW

**Comment by Bravyn** [comment]
Kindly send me the api key

**Comment by Paul-Ndirangu** [comment]
OPENAI_API_KEY="sk-proj-8ZR9IzAoXZsDjv0QMPI7T3BlbkFJF2JAl5AMMRRoPdgoOQYP"



Paul Ndirangu
+254725208403
https://www.linkedin.com/in/paul-ndirangu/
Data Scientist

**Comment by Paul-Ndirangu** [comment]
Use this api key instead:
sk-proj-8ZR9IzAoXZsDjv0QMPI7T3BlbkFJF2JAl5AMMRRoPdgoOQYP

Best regards,

Paul Ndirangu
+254725208403
https://www.linkedin.com/in/paul-ndirangu/
Data Scientist

**Comment by Bravyn** [comment]
Thanks, I'll check it out!

**Pull request merged**
